name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e29ca46b1fe1fc41e1f8aae05ef96f9478a57c5e4315614ddd87b7877c15f00d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
