name = "Meloncraft 1.2.2"
author = "vids_by_melon"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "907ccdef83fd1cecb8a2d6e4f77f0cc0203a081cc1adb5114e7d26b1b5fa5e8e"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
