name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40666a47c79fceb10021a32e51e6c612279fa76c186787026ea9b4ec85dfbf8a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
