name = "Meloncraft 1.5.0"
author = "vids_by_melon"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e58b20c9cc160361671275a489f5072b828e7e27ef037bbc6168c08f1f51c6db"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
