name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c66b7abf3022f45c7a7f78734c76e878da1faf33d78163bcc18d884fa437f132"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
