name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dab89af32d9c8ab0616ae22d072afb18264196a2208e2ccf2a3650776a175f39"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
