name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "601df3f894bba9517fb3c31fe8de1967f77c18732604e193b896e0ec39c67858"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
