name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5768bbadd5d115ea9ab879d883fc50064914de2ceceabeea0516707f3145b5f1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
