name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96791d77561532432e690bcccc6ebb000b43f03eeb33971d748724115c45f10c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
