name = "Meloncraft 1.5.0"
author = "vids_by_melon"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ff58d0d1aa7cb8dbe46d14fc927d63ffcb5aadc070a9ab57f37487da02ec35b"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
