name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29d903091ae075e17291991f6c7174b47488fc40cbe976481aa93a36fe3bceac"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
