name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2adb28daf1dd6ab4db13b82ef1266062a13f88733bb361ba8268f0d860a66c6"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.103"
