name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c04d115e74e87c8f484aa71d98590f5bc58f5600f3e6a82be0f22208d15ec8f1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
