name = "Meloncraft 1.4"
author = "vids_by_melon"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83f2fd1e1acc041bf4d8f150b18c69eaecec6074d80195de2ede359968215cbb"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
