name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a0db12d2105e9bbef8db742c2f0e0e58028e275c60023a12af44f21066da13f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
