name = "Meloncraft 1.4.3"
author = "vids_by_melon"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4ccd97f88d33ae39dd2868e3330251a7abb6aaad6816e721d75dd0199e50a33"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
