name = "Meloncraft 1.5.1"
author = "vids_by_melon"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac0bc17eada36f269bd956ebc934c90516310354965b90d8c574f97234b974ca"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
