name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8725bc7b9b64f9df67e9713c643f116f0122e01c56b2de5d28af4eaac33bef57"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.103"
