name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "242fd4d73ebcbccd623e75ba91ae9afbfb51bf2fe952edaf4704e3c34f7c3f0a"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.103"
