name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26056d9236c88aacc1ab82a4c344f0544b340f630e4d6135a441b14c1bae80c2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
