name = "Meloncraft 1.4.1"
author = "vids_by_melon"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bf1ebc117677ecd17309735c7648ede9348dcb1799aa75f3b7e2d22c0458f7b"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
