name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c42398e46665d0ab1f22a4cef4a04ecd064729c4a17ec3f68711076706b365"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
