name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1f6efa1de588426366e1e802682067877b44f290485448a0652674e735c4083"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
