name = "Meloncraft 1.3"
author = "vids_by_melon"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc1bfc5074c752a364970a956b99c96857f18ab05128993d0d794d86927e360a"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
