name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b3cc62b1edaf89e11ac3d988dd30c8c90b9f8a3f1b33583daa9d20924f58aae"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
