name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73ec41d2778c62fe26f9c9fcb04dbd35da44d5334fe267667d90887758af4e03"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
