name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ef3bc29124b8669e5ca6c56937d46525d717d5edcdad8e5d67d07b476a0aec9"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0-beta.2"
