name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a79eb18ed5ab5ad3d71def441704e2f4d860e4bc9a4709c4b5c8772854a7be2"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.103"
