name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccd17027ae3045ecb3bb134e1114822866a3b47dbcf681cae61047b4999f6bfc"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
