name = "Meloncraft 1.2.2"
author = "vids_by_melon"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f612e87686d8eb936cf57bb375bf3c93ec339b4ec917c21977034ce87e4a04f7"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
