name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3d485ba93d0e283fe66e880106b2210772c2c1a93d6896d29996c45714057ba"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
