name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c280a542f4d326cee6aac518985710e7e4b5d18cffd2c0879493ea25b5b53d6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
