name = "Meloncraft 1.5.1"
author = "vids_by_melon"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9daf44240676e7376aec6bd6bbcb5c7b9743c87fb24294d8320a1d496059619"

[versions]
minecraft = "1.20.1"
neoforge = "latest"
