name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38144fa8cc6b25e82b1d44bec27851f4244c8dcb90dd871cb4e5101bba0c3190"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
