name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a625844f0735a5f0ca1dca429cce2fb4500c076a9d0229fb20d644ef43adce35"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
