name = "Meloncraft Modpack"
author = "vids_by_melon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ca379543482580c46b61ca85672fa591b1f867cbaddc8e80afc5569c8bbbb93"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
